name: Update arXiv Papers

on:
  schedule:
    # Run at 00:00 on the 1st day of every month
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch: # Allows you to run it manually anytime

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download arXiv Feed
        run: |
          # Replace with your actual arXiv URL
          curl -o public/papers.xml "https://arxiv.org/a/martinezmunoz_a_1.atom"

      - name: Commit and Push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/papers.xml
          # Only commit if the file has changed
          git commit -m "Auto-update arXiv papers" || exit 0
          git push
